Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'  # Avoid "Access is denied" error when running via SSH

Push-Location (Split-Path (Get-Variable MyInvocation -Scope Script).Value.MyCommand.Path)  # Change working directory to script directory

echo 'Trying to clean-up old test installation:'
dir

Remove-Item ow-forecasting-install -Recurse -ErrorAction Ignore -Force  # Delete previous installation

echo 'Old test installation should have been cleaned-up:'
dir

Expand-Archive -LiteralPath ow-forecasting-install.zip -DestinationPath ow-forecasting-install

Push-Location ow-forecasting-install

function Extract-Zip($name)
{
    Expand-Archive -LiteralPath "${name}.zip" -DestinationPath "${name}-tmp"
    Move-Item -LiteralPath "${name}-tmp/${name}" -Destination "${name}"
    Remove-Item -LiteralPath "${name}-tmp" -Recurse
}

Extract-Zip "forecasting_platform"
Extract-Zip "owforecasting"
Extract-Zip "00 Config"
Extract-Zip "01 Raw data"
Extract-Zip "expected_results"

New-Item -ItemType Directory "./test-results/backward-run"
New-Item -ItemType Directory "./test-results/development-run"
New-Item -ItemType Directory "./test-results/production-run"

Copy-Item "$HOME/ow-forecasting-mapping/identifier.csv" -Destination "./00 Config"

echo 'Setup of files for platform completed:'
dir

$env:Path="C:\Program Files\Python38;$env:Path"
echo $env:Path

if (Test-Path "C:\ProgramData\Miniconda3\Scripts\conda.exe")
{
    # This code is usually generated by running `conda init powershell`, but as we don't want to change
    # the user environment, we inline the setup of the correct PATH in a conda installation here
    (& "C:\ProgramData\Miniconda3\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
}

$venvDirectory = '../ow-forecasting-venv'  # Allow to reuse same virtualenv between different installation runs

python --version
python -m venv $venvDirectory
. "$venvDirectory/Scripts/Activate.ps1"

pip install poetry==1.0.5
poetry env info
poetry env list
poetry config virtualenvs.create false
poetry install --no-dev --extras poetry
